# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fv32VIIzrY-RW07Q8mj5HZ-ubUGAKGhe
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import io

class DataLoader:
    def __init__(self):
        self.data = {}

    def load_file(self, file_type='csv'):
        """Ładowanie pliku CSV lub TXT do Pandas DataFrame"""
        uploaded = files.upload()
        for filename in uploaded.keys():
            print(f"Ładowanie pliku: {filename}")

            if file_type == 'csv':
                self.data[filename] = pd.read_csv(io.BytesIO(uploaded[filename]))
            elif file_type == 'txt':
                self.data[filename] = pd.read_csv(io.BytesIO(uploaded[filename]), delimiter='\t', header=None)
            else:
                print("Nieobsługiwany format pliku!")
                return

            print(f"Załadowano: {filename}")

    def show_data(self):
        """Wyświetlanie załadowanych danych"""
        if not self.data:
            print("Brak załadowanych plików!")
            return

        for filename, df in self.data.items():
            print(f"\nPodgląd danych z: {filename}")
            display(df.head())

    def normalize_and_compute_distances(self):
        """Normalizacja danych i obliczenie odległości euklidesowych"""
        if not self.data:
            print("Brak załadowanych plików!")
            return

        for filename, df in self.data.items():
            print(f"\nPrzetwarzanie danych z: {filename}")
            numeric_df = df.select_dtypes(include=[np.number])  # Wybór tylko kolumn numerycznych
            if numeric_df.empty:
                print("Brak danych numerycznych do przetworzenia!")
                continue

            max_abs_values = numeric_df.abs().max()
            normalized_df = numeric_df / max_abs_values  # Normalizacja względem maksymalnej wartości modułu

            distances = np.linalg.norm(normalized_df, axis=1)  # Obliczenie odległości euklidesowych
            sorted_indices = np.argsort(distances)  # Sortowanie według odległości
            sorted_distances = distances[sorted_indices]

            print("Posortowane odległości od początku układu współrzędnych:")
            print(sorted_distances)

            # Rysowanie wykresu logarytmicznego odległości
            plt.figure(figsize=(8, 5))
            plt.plot(np.log1p(sorted_distances), marker='o', linestyle='-')  # Skala logarytmiczna
            plt.xlabel("Indeks posortowanego przykładu")
            plt.ylabel("Logarytm odległości")
            plt.title("Posortowane odległości euklidesowe (w skali logarytmicznej)")
            plt.grid()
            plt.show()

# Przykładowe użycie w Google Colab
loader = DataLoader()
print("Wgraj plik CSV lub TXT:")
loader.load_file(file_type='csv')  # Zmień na 'txt' dla plików tekstowych
loader.show_data()
loader.normalize_and_compute_distances()